### ISSUE TITLE
bigint in postgres returns string type in json

### ISSUE THREAD

**Issue by beinginorbit** [waterlinejs/postgresql-adapter#10]
I just recently migrated from mysql to postgres and during the data transfer pgloader converted all integers and ids into bigint and bigserial.

It seems waterline doesn't cast those to integer properly, returning string type instead. This happens both for this adapter and the built in sails adapter.

Thanks for the hard work on this adapter everyone. :+1:

**Comment by tjwebb** [comment]
This is an issue with the `pg` driver itself; here is one workaround: 

``` js
pg.types.setTypeParser(20, 'text', parseInt);
```
