### ISSUE TITLE
Apostrophes in enumerated string validations cause invalid SQL

### ISSUE THREAD

**Issue by mcodev1** [waterlinejs/postgresql-adapter#14]
Using an apostrophe `'` in an enumeration will cause an error when the `CREATE TABLE` command is generated, as the apostrophe isn't properly escaped.

**Comment by tjwebb** [comment]
> Using an apostrophe ' in an enumeration

e.g. 

``` js
{
  type: 'string',
  enum: [
    'this\'ll break',
    "it's broken"
  ]
}
```

like that?

**Comment by mcodev1** [comment]
Yeah the second line with a single quote inside double quotes, though now I can't recreate the error.

When it was happening I didn't keep digging into the reason why and I should have. I know it was during lift with a connection to an empty Postgres database. The error was something like "invalid syntax" and listed a `CREATE TABLE` SQL command that ended in the enumerations like `word word wor'` <- with the single quote at the end, which was in the middle of a word. It went away as soon as I removed the single quote. I wish I knew what happened.

**Comment by mcodev1** [comment]
I'll be more careful to save the exact error and take note of the state of my code so I can create more useful GitHub issues.
