### ISSUE TITLE
Support for JSONB

### ISSUE THREAD

**Issue by omidh28** [waterlinejs/postgresql-adapter#29]
Is JSONB supported? Or is there any plan to support it?

**Comment by tjwebb** [comment]
jsonb is indeed suported: https://github.com/waterlinejs/postgresql-adapter/blob/5fd72e442d1476041150cd44ed5959bc17cbc4ce/lib/util.js#L301-L302

Let us know if you have problems, thanks!

**Comment by omidh28** [comment]
Thank you for your response, Can also I use it with sails-postgres?
