### ISSUE TITLE
Unable to pass JSON Array as parameter

### ISSUE THREAD

**Issue by KyleLilly** [waterlinejs/postgresql-adapter#5]
Currently it's not possible to pass a JSON array as a query parameter. This is due to the following function in [util.js](https://github.com/waterlinejs/postgresql-adapter/blob/master/lib/util.js#L300)

```
if (_.isString(value) && value[0] === '[') {
    let arr = JSON.parse(value)
    if (_.isArray(arr)) {
        return arr
    }
}
```

Per a discussion on the node-postgres issue board https://github.com/brianc/node-postgres/issues/442 - since arrays were around before json the preferred approach is to use `JSON.stirngify()` if you want to pass an array. This works in sails-postgres but fails in this updated knex based adapter.

**Comment by tjwebb** [comment]
So first of all, I'm pretty sure we went to Virginia Tech together :)

Secondly, yea that looks like an issue. If you think you have a quick fix, I'd be happy to merge a Pull Request.

**Comment by KyleLilly** [comment]
Yeah BT Tracker - didn't realize it was you. I'll get a PR together once I get some tests written.

**Comment by tjwebb** [comment]
Haha awesome, thanks.
